### ISSUE TITLE
ezANOVA(..., return_aov = TRUE) yields an aov object that cannot be used with stats::TukeyHSD()

### ISSUE THREAD

**Issue by mike-lawrence** [mike-lawrence/ez#3]
This is because the aov formulae used by ezANOVA always include an Error() term, regardless of whether it is needed. The solution is to only include the Error() term when there are within variables that necessitate it.

**Comment by eherschel** [comment]
hi Mike! I'm currently trying to use this feature so I can perform post-hoc tests. Here is my code:

affil_in<-ezANOVA(data = aff_in, 
                    dv = in_affil, 
                    wid = id,
                    within = time,
                    between = condition,
                    between_covariates = c(iri, goldsmith, psync),
                    return_aov = T,
                    detailed = T)

However, I dont see how I can use the output from return_aov for post hoc tests. 

The output is as follows:

affil_in$aov

Call:
aov(formula = formula(aov_formula), data = data)

Grand Mean: 11.09596

Stratum 1: id

Terms:
                condition Residuals
Sum of Squares     2.7349  969.1905
Deg. of Freedom         1        97

Residual standard error: 3.160958
1 out of 2 effects not estimable
Estimated effects are balanced

Stratum 2: id:time

Terms:
                     time condition:time Residuals
Sum of Squares    9.33838       20.20642 110.95520
Deg. of Freedom         1              1        97

Residual standard error: 1.069518
Estimated effects may be unbalanced

I have tried the following two post hocs and get the following errors:

TukeyHSD(affil_in$aov)
Error in UseMethod("TukeyHSD") : 
  no applicable method for 'TukeyHSD' applied to an object of class "c('aovlist', 'listof')"

HSD<-HSD.test(affil_in, "time", group = FALSE, console = TRUE)
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) : 
  cannot coerce class ‘c("aovlist", "listof")’ to a data.frame

Thanks very much for your help

**Comment by mike-lawrence** [comment]
Have you tried the afex package? That’s pretty much the successor to ez, and I haven’t done any update work on ez for over a decade so it’s possible ez broke in the interim.  Sent from Proton Mail for iOS On Sun, Feb 26, 2023 at 12:54 AM, eherschel ***@***.***> wrote:  
hi Mike! I'm currently trying to use this feature so I can perform post-hoc tests. Here is my code:
affil_in<-ezANOVA(data = aff_in,
dv = in_affil,
wid = id,
within = time,
between = condition,
between_covariates = c(iri, goldsmith, psync),
return_aov = T,
detailed = T)
However, I dont see how I can use the output from return_aov for post hoc tests.
The output is as follows:
affil_in$aov
Call:
aov(formula = formula(aov_formula), data = data)
Grand Mean: 11.09596
Stratum 1: id
Terms:
condition Residuals
Sum of Squares     2.7349  969.1905
Deg. of Freedom         1        97
Residual standard error: 3.160958
1 out of 2 effects not estimable
Estimated effects are balanced
Stratum 2: id:time
Terms:
time condition:time Residuals
Sum of Squares    9.33838       20.20642 110.95520
Deg. of Freedom         1              1        97
Residual standard error: 1.069518
Estimated effects may be unbalanced
I have tried the following two post hocs and get the following errors:
TukeyHSD(affil_in$aov)
Error in UseMethod("TukeyHSD") :
no applicable method for 'TukeyHSD' applied to an object of class "c('aovlist', 'listof')"
HSD<-HSD.test(affil_in, "time", group = FALSE, console = TRUE)
Error in as.data.frame.default(x[[i]], optional = TRUE, stringsAsFactors = stringsAsFactors) :
cannot coerce class ‘c("aovlist", "listof")’ to a data.frame
Thanks very much for your help
