### ISSUE TITLE
.() list - Documentation Clarification

### ISSUE THREAD

**Issue by joobei** [mike-lawrence/ez#53]
The docs for ezANOVA state that the arguments for within "must be specified as a .() list". I found this to be confusing. I thought a ".() list" is a special kind of list and ended up googling around for it before even trying a normal c(..) list. Perhaps this is because I'm not such a pro in R but nevertheless I think just saying list without the .() parentheses might be better. 

Just my 2 cents.

**Comment by mike-lawrence** [comment]
A "list" is a specific object type in R, created via the "list()" function. A ".() list" is a different object type, borrowed from the plyr library. I'll keep it as is with the addition of a parenthetical to see examples section for usage.
