### ISSUE TITLE
return_aov = T causes ezANOVA to hang

### ISSUE THREAD

**Issue by GarryGelade** [mike-lawrence/ez#55]
[test_data.zip](https://github.com/mike-lawrence/ez/files/1655690/test_data.zip)

`d <- readRDS("test_data.RDS")

anova_rm <- ezANOVA(data=d,
                    dv = vChange,
                    wid = .(sec.no),
                    within = .(Condition.f),
                    detailed = T,
                    return_aov = T)`

> The function runs OK if return_aov is false, but seems to loop without completeion if return_aov is True.

**Comment by mike-lawrence** [comment]
Seems to be an issue with `stats::aov` and the number of levels that `sec.no` has. It actually isn't hanging, but takes 40mins and uses 7GB of RAM. You might post this to the R-help mailing list, maybe just saying that you are trying to run `stats::aov(y ~ x+Error(z/x))` when z is a factor with 6554 levels and it's taking lots of time & RAM and asking if this should be expected.
