### ISSUE TITLE
How to set dynamic values to ezANOVA function?

### ISSUE THREAD

**Issue by zuooonz** [mike-lawrence/ez#62]
for example:

dv <- "Group“
ezANOVA( ... dv = get(dv) or as.name(dv) or other tricks ...)

I need to call ezANOVA in my owen function, repeatedly, with different dv.

**Comment by mike-lawrence** [comment]
I tried a bunch of stuff to try to get this to work using base::eval, dplyr::enquo, etc, but couldn't get anything to work. Instead, I realized that at least for the case of multiple dv's in the same data set, this pipe works:

```
library(tidyverse)
library(ez)
data(ANT) #example data supplied by ez

#start a pipe with ANT
ANT %>% 
	#collect dv's to analyze
	tidyr::gather(
		key = dv
		, value = value
		, 'rt'
		, 'error'
	) %>% 
	#create a copy of dv for printing what dv is being analyzed
	dplyr::mutate(
		dv_ = dv
	) %>% 
	#nest all columns except original dv column
	tidyr::nest(
		-dv
	) %>% 
	#group by original dv column
	dplyr::group_by(
		dv
	) %>% 
	# compute the analysis on each dv
	dplyr::summarize(
		out = purrr::map(
			data
			, function(x){
				print(x$dv_[1])
				out = ezANOVA(
					data = x
					, dv = value
					, wid = subnum
					, within = cue
				)
				print(out)
				return(out)
			}
		)
	) %>%
	# unnest
	tidyr::unnest(out)
```

**Comment by zuooonz** [comment]
Thank you for your reply. 
Wishing there will be an ez way to passing variable to ez functions.

**Comment by mike-lawrence** [comment]
Here's a simpler, but still kludge-y, solution:

```
library(ez)
data(ANT)

f = function(dv){
	ANT$dv = ANT[,names(ANT)==dv]
	ezANOVA(
		data = ANT
		, dv = dv
		, wid = subnum
		, within = .(cue,flank)
		, between = group
	)
	
}

f('rt')
f('error')
```

This assumes you don't have a variable already called `dv` in the data; else use another dummy name.

**Comment by mike-lawrence** [comment]
If you feel like contributing, I think the solution is to replace the kludge-y code in [lines 22-40 here](https://github.com/mike-lawrence/ez/blob/master/R/ezANOVA.R#L22) with proper [tidy evaluation](https://adv-r.hadley.nz/evaluation.html).

**Comment by zuooonz** [comment]
Well, I recommend [afex](https://github.com/singmann/afex).
