### ISSUE TITLE
ezANOVA throws "missing values error"

### ISSUE THREAD

**Issue by Narendra-IITRopar** [mike-lawrence/ez#63]
Hi Mike,

**I am running the following code:**
`library(ez)

data_time <- read.table('input_anova.txt', header = TRUE)

data_time$subj = as.factor(data_time$subj)
data_time$itm = as.factor(data_time$itm)

ezANOVA(data_time,dv = ansj,wid=subj,within=.(anim,noun))`

**it throws the following error:**

Error in ezANOVA_main(data = data, dv = dv, wid = wid, within = within,  : 
  One or more cells is missing data. Try using ezDesign() to check your data.

**When I checked the data using ezDesign and ezPrecise, they don't show any missing value, the output of **

`ezPrecise(data_time, transpose = TRUE)`

**is as below** 

Data frame dimensions: 3360 rows, 13 columns
             type missing values  min   max
subj       factor       0     21    2    23
ses       numeric       0      2    1     2
hand       factor       0      2 left right
cond       factor       0      4  ala   ilc
itm        factor       0    320  101   480
anim       factor       0      2    a     i
noun       factor       0      2    a     c
acc_resp  numeric       0      3    0     4
ansj      numeric       0      2    0     1
acc_rt    numeric       0    971    0  1499  
prob_resp numeric       0      3    0     4
prob_rt   numeric       0    818    0  1924
ansprob   numeric       0      2    0     1

**kindly help me in resolving the issue. **

Thanks!

Regards,
Narendra

**Comment by mike-lawrence** [comment]
Sorry, I missed this until just now. ezDesign should produce a plot. What does the following produce?

```
ezDesign(
    data = data_time
    , x = subj
    , y = anim
    , col = noun
)

**Comment by mike-lawrence** [comment]
Closing as I received no response
