### ISSUE TITLE
ezBoot & ezPlot2

### ISSUE THREAD

**Issue by suwolff** [mike-lawrence/ez#66]
Hi,

when calculating bootstrap confidence intervals, there are typically several options for how to calculate them; e.g. percentile CI, normal CI, bias-corrected accelerated CI etc. 

Since it is widely recommended, I would like to report the bias-corrected accelerated (BCa) CI. However, i cannot find the part of the ezPlot2 function where I can select the type of CI, and I do not know which is the default type.

Could you please help me? Is there a way to get the BCa CIs within the ez package?

Thank you very much in advance!

**Comment by mike-lawrence** [comment]
Hey there, honestly you shouldn't use ez for bootstrapping. I included it over a decade ago without much expertise in the domain and feel like other packages would have more options & be backed by more expertise. Frankly, I've moved on to a Bayesian framework for inference and where most of ez's features have been replicated then surpassed by the afex package, I should probably shut down ez itself.

**Comment by suwolff** [comment]
Thank you for your swift response! Sad to hear that you might shut ez down, but thank you for the advice, I will look into the afex package. Does it also offer an alternative to ezPerm?

**Comment by mike-lawrence** [comment]
> I will look into the afex package. Does it also offer an alternative to ezPerm?

I don't believe so, but you should double-check. Honestly, if you are worried about the restrictive assumptions of standard ANOVA/regression tools, while I can appreciate your interest in "non-parametric" alternatives like bootstrapping and permutation tests (I was a big fan of those myself long ago, hence their inclusion in ez), I've more recently come to the opinion that (1) "non-parametric" is a misnomer, and they should really be called "obscurely parameterized" tools, and (2) the solution to data that violate the assumptions of traditional tools isn't to seek tools that have less parametric structure but to move to tools that enable you to have *more* parametric structure. If you transition to a Bayesian framework you can build your models with whatever structure you want, including all kinds of measurement noise distributions, hierarchical structure, latent structure, mixture distributions, etc. I now use [Stan](mc-stan.org) for my everyday statistical practice and have [a lecture series here](https://www.youtube.com/playlist?list=PLu77iLvsj_GNmWqDdX-26kZ56dCZqkzBO) that walks through Bayesian implementations of common models.

**Comment by suwolff** [comment]
Thank you very much! 
Yes, Bayesian analysis has also been on my to-do list for a while, and it seems I should get into it soon.
Thanks again for responding so promptly, it is a pleasure to work this way :)
